### ISSUE TITLE
needs more jquery

### ISSUE THREAD

**Issue by AKST** [mrkrstphr/illacceptanything#141]
We need more jquery

**Comment by cgaudreau** [comment]
Brilliant. Can I hire you as a full-stack big data web engineer?

**Comment by AKST** [comment]
Is there a jquery plugin for that?

**Comment by lachlanmcdonald** [comment]
Mandatory "you can do it without jQuery" comment.

**Comment by vhakulinen** [comment]
but...but my frameworks!

**Comment by CptnBrittish** [comment]
We can use both frameworks and jQuery in the webapp which is developing in the pull request queue. First we need to change to a organization though so that we can develop this rapidly enough.
