### ISSUE TITLE
Add a Vagrantfile

### ISSUE THREAD

**Issue by jackyliang** [mrkrstphr/illacceptanything#22]
Add a Vagrantfile because it is web scale and deployment machine will be the same as development

**Comment by weswigham** [comment]
See #29 - a Dockerfile's like the same thing but better, amirite? (After all, Vagrant support docker!)

**Comment by Vheissu** [comment]
Everyone knows that only MongoDB is web scale.

**Comment by jackyliang** [comment]
@weswigham In all seriousness, Docker is better than Vagrant is that true?

**Comment by weswigham** [comment]
They don't (quite) serve the same purpose. Vagrant can configure environments, and so can docker - thing is, docker is made for configuring containers while vagrant configures virtual machines. [Vagrant actually supports using docker as a provider](http://docs.vagrantup.com/v2/docker/basics.html). Personally, I think the docker ecosystem ([dockerhub included](https://registry.hub.docker.com/search?q=library)) has progressed to be more useful than its vagrant counterpart ([which would be vagrant cloud/atlas, I believe](https://atlas.hashicorp.com/boxes/search?utm_source=vagrantcloud.com&vagrantcloud=1)). That is to say, it's typically easier to find a container which already has what you want than a vagrant box which does. I also believe docker's tooling environment has made it easier to orchestrate a system of containers compared to the tools Hashicorp has made for Vagrant for orchestrating systems of VMs.
